### ISSUE TITLE
Question related to Github 

### ISSUE THREAD

**Issue by Aju100** [anuraghazra/anuraghazra#1]
let's say i sent out PR to one opensource project and it got rejected. again i looked into another new issue, i solved it and i am creating that issue. but i have code which has been rejected too now how to successfully send PR

**Comment by anuraghazra** [comment]
You should checkout to the latest branch of the remote repo and create a new branch on top of it and then start working... whenever you work on a issues create a new branch for it separately

**Comment by Aju100** [comment]
oh thank u bro. but is this a way to communicate or something else?

**Comment by anuraghazra** [comment]
> but is this a way to communicate or something else?

Sorry could not understand what do you mean.. in which context?

**Comment by Aju100** [comment]
nothing bro thanks for info

**Comment by anuraghazra** [comment]
@Aju100 let's see your stats :smile: 
![Aju's github stats](https://github-readme-stats.vercel.app/api?username=Aju100)

**Comment by Aju100** [comment]
how did u do it bro ?

**Comment by anuraghazra** [comment]
@Aju100 

[![ReadMe Card](https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats)](https://github.com/anuraghazra/github-readme-stats)

**Comment by anuraghazra** [comment]
Thanks for asking the question @Aju100 I hope you got your answers. Closing this now 👌
