### ISSUE TITLE
How did you thought about idea of GitHub Readme Stats?

### ISSUE THREAD

**Issue by abhinavg916** [anuraghazra/anuraghazra#13]
I am impressed to see your creativity!
Feel proud you are from India.

**Comment by anuraghazra** [comment]
Thanks @abhinavg916

well, i just got the idea suddenly and just made the prototype in 15mins and i left it did not actually published it then after some time i though "Okay whatever lets just share it on github" and i saw people actually liked it, and it was really unexpected.

**Comment by abhinavg916** [comment]
Good Work!
