### ISSUE TITLE
Returning individual status

### ISSUE THREAD

**Issue by madeindra** [anuraghazra/anuraghazra#17]
Hi @anuraghazra 

First of all, let me tell you that you did awesome works!

I've been wanting to let the API return individual value so that I can customize my readme without the card, can you do this modification?

I already did some crude modification on my fork (https://github.com/madeindra/github-readme-stats) to enable this API function, but it's so crude, I'm not that good with javascript for now and I've not even written a unit test for that.

**Comment by anuraghazra** [comment]
Hi @madeindra  Do you want to be able to get a JSON instead of the rendered SVG?

**Comment by anuraghazra** [comment]
@madeindra Oh okay thats cool
![individual_v](https://user-images.githubusercontent.com/35374649/88476703-37e44580-cf58-11ea-8ff0-1c03383ac560.PNG)

**Comment by anuraghazra** [comment]
@madeindra please open a new feature request at https://github.com/anuraghazra/github-readme-stats/issues

**Comment by madeindra** [comment]
Thanks! I will open a feature request
