### ISSUE TITLE
Git question

### ISSUE THREAD

**Issue by Aju100** [anuraghazra/anuraghazra#18]
@anuraghazra Let's say I have an opensource project where I accidentally pushed the secret key and I again removed nad pushed again to the repo. And guess hacker can look up my git commit history and can get the secret key. Is there any way to solve it instead of deleting whole repo?

**Comment by anuraghazra** [comment]
Maybe this helps 
https://docs.github.com/en/github/managing-large-files/removing-files-from-a-repositorys-history

**Comment by Aju100** [comment]
@anuraghazra  thanks mate

**Comment by anuraghazra** [comment]
I hope you resolved this @Aju100. Closing this.
