### ISSUE TITLE
Language/Tool icons

### ISSUE THREAD

**Issue by dougwaldron** [anuraghazra/anuraghazra#20]
Hi! Where did you get the icons for the languages & tools section of your README?

**Comment by Dev-CasperTheGhost** [comment]
Hi @dougwaldron,

You can copy the image address from the GitHub Topic page E.G: _(sorry for bad gif quality, something went wrong when converting)_
![gif](https://media.giphy.com/media/YQHhTDWbfw5zTeRjs9/giphy.gif)

Or steps:

1. Search for the github topic you want a icon from
2. Most topic will have info about them at the top, and an icon
3. Right click the icon and select "Copy Image Address"
4. Done!

**Comment by dougwaldron** [comment]
Ok, cool, I never noticed the topics page. Thanks!
