### ISSUE TITLE
Most used language stats dont reflect contributions to private repos.

### ISSUE THREAD

**Issue by lopezdp** [anuraghazra/anuraghazra#21]
Thank you for building this tool, I love it and it is great!

I noticed that the most used language stats do not reflect contributions to private repos. Is there anything we can do to add a show private query param the same way we do with the GH stats?

Thank you and much appreciated! Feel free to email me as needed: davidplopez@live.com

**Comment by anuraghazra** [comment]
It is not possible to fetch private repo information without having access to the user's account.

The only possible way is to host on your own vercel instance with your own PAT that way you can access the private repos.

**Comment by lopezdp** [comment]
> It is not possible to fetch private repo information without having access to the user's account.
> 
> The only possible way is to host on your own vercel instance with your own PAT that way you can access the private repos.

Thank you for the quick response, I really appreciate it. One last thing, what do you mean by **PAT**??

**Comment by anuraghazra** [comment]
Github PAT (Personal Access Token) https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance

**Comment by lopezdp** [comment]
@anuraghazra it worked out pretty good, your docs on deploying the server to Vercel are pretty good. The only thing I noticed is that to get it to work, I have to provide a lot more permission for the PAT to access my code than I am comfortable with. How can we restrict the needed permissions to READ_Only only and still have the cards work accordingly? READ ONLY is currently not sufficient enough.

**Comment by anuraghazra** [comment]
> I have to provide a lot more permission for the PAT to access my code than I am comfortable with.

You have to provide those information if you wanted to access private repos, although note that it's your fork, your vercel instance, your env variable so it's totally safe as long as you don't leak your access token somehow.

**Comment by lopezdp** [comment]
> > I have to provide a lot more permission for the PAT to access my code than I am comfortable with.
> 
> You have to provide those information if you wanted to access private repos, although note that it's your fork, your vercel instance, your env variable so it's totally safe as long as you don't leak your access token somehow.

😂 what security protocol?! My password is 1-2-3-4-5!

![SpaceBalls](https://www.youtube.com/watch?v=_JNGI1dI-e8)
