### ISSUE TITLE
How can i return code in browser in serverless

### ISSUE THREAD

**Issue by vimalverma558** [anuraghazra/anuraghazra#24]
Hey, I want to return `svg` in browser, but it return with `html body` tag, How can i return only `svg`

Please provide any blog or Video link(if Possible)

**Comment by anuraghazra** [comment]
Set proper response headers

Use response.setHeader method ->

https://github.com/anuraghazra/github-readme-stats/blob/461a022d2f077c6e0e8c710fcc2221f1651b7938/api/index.js#L36

**Comment by vimalverma558** [comment]
Thanks 🙏
