### ISSUE TITLE
I need some Full-Stack Project Ideas?

### ISSUE THREAD

**Issue by vikasganiga05** [anuraghazra/anuraghazra#35]
Hi, I am a full-stack developer I want to create a project for my portfolio. Please suggest me some good and unique project ideas to make my portfolio standout.
Thank You :pray:

**Comment by ReactifyStudio** [comment]
Hey @vikasgania05. I want to work on my portfolio as well. Help us @anuraghazra @eddiejaoude

**Comment by eddiejaoude** [comment]
I would have 2 types of projects

- more feature rich project, something like: job board, twitter clone
- smaller project that is fully automated with CI and CD

**Comment by vikasganiga05** [comment]
> I would have 2 types of projects
> 
> * more feature rich project, something like: job board, twitter clone
> * smaller project that is fully automated with CI and CD

Thank You :pray:

**Comment by anuraghazra** [comment]
Thanks for the answer @eddiejaoude 

Yes i would also recommend

1. Realtime video chat app, (Web RTC)
2. BugTracker similar to my project bugvilla. 
3. Twitter like platform where users can only upload small snippets of code (and can be executed live)

**Comment by vikasganiga05** [comment]
> Thanks for the answers @eddiejaoude
> 
> @vikasganiga05 Yes i would also recommend
> 
> 1. Realtime video chat app, (Web RTC)
> 2. BugTracker similar to my project bugvilla.
> 3. Twitter like platform where users can only upload small snippets of code (and can be executed live)

Thank You for the suggestions :pray:

**Comment by vikasganiga05** [comment]
Thanks for the project ideas it helped me a lot :pray:
