### ISSUE TITLE
Which is the best way to build a personal portfolio or a blog?.

### ISSUE THREAD

**Issue by ReactifyStudio** [anuraghazra/anuraghazra#36]
I am thinking of building a complex personal portfolio that includes stuffs like server side rendering, being abit more dynamic and such. It will also have a personal blog feature and a feature to showcase everything in real-time. Is normal HTML, CSS, JS or React like Gatsby and Next.js needed? @anuraghazra @eddiejaoude .

**Comment by eddiejaoude** [comment]
Hi @Qodestackr , did you mean to close this? Did it get moved to a GitHub Discussion?

**Comment by Qodestackr** [comment]
What I wanted is an advice. I saw your video at traversy media about open source and I was interested in trying pull requests and such. @eddiejaoude .

**Comment by Qodestackr** [comment]
I guess I have the required stack to complete it.

**Comment by eddiejaoude** [comment]
Might be better if you chat to the community in Discord discord.eddiehub.org
