### ISSUE TITLE
readme stats not working

### ISSUE THREAD

**Issue by NirmalSilwal** [anuraghazra/anuraghazra#39]
Hello @anuraghazra the github readme stats is not loading properly. Are there any updates/dependencies pending or anything else you're working on it?

![stats](https://user-images.githubusercontent.com/31946761/115173655-6527e380-a0e5-11eb-9324-530baffdf36b.PNG)

**Comment by anuraghazra** [comment]
Seems to be working. something went wrong while fetching the stats that time i guess.

**Comment by NirmalSilwal** [comment]
yes, it's working now
