### ISSUE TITLE
How to Hide c# and c++ languages on git stats

### ISSUE THREAD

**Issue by rodrigozegobia** [anuraghazra/anuraghazra#72]
Hi, Anuraghazra. I love the git stats you made.
There is a "&hide=" feature for hiding languages. I was able to make it working for javascript, css, html but not for c# and c++. What do i need to write? I tried cpp, csharp, c++, c# and  all previous with uppercase C . None worked.
Thanks!

**Comment by mkredzel** [comment]
Hi @rodrigozegobia,

This should resolve your issue.

> **Warning**
> Language names should be URI-escaped, as specified in [Percent Encoding](https://en.wikipedia.org/wiki/Percent-encoding)
> (i.e: `c++` should become `c%2B%2B`, `jupyter notebook` should become `jupyter%20notebook`, etc.) You can use
> [urlencoder.org](https://www.urlencoder.org/) to help you do this automatically.

https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options

**Comment by rodrigozegobia** [comment]
Hi Marcel,
I believe that solved the issue.
Thank you a lot.
