### ISSUE TITLE
Hi anuraghazra

### ISSUE THREAD

**Issue by dunz** [anuraghazra/anuraghazra#8]
Thank you very much for sharing this good source.

I have a question.

```md
<img height="20" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png">
```
The icons you used are cute.
I want to know the origin of this route.
Other icons are needed.

**Comment by dunz** [comment]
> Thank you very much for sharing this good source.
> 
> I have a question.
> 
> ```lisp
> <img height="20" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png">
> ```
> 
> I want to know the origin of this route.
> Other icons are needed.

**Comment by anuraghazra** [comment]
origin of those icons are from here https://github.com/topics
